apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-dns
  namespace: networking
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cloudflare-dns-vault
  namespace: networking
spec:
  provider:
    vault:
      server: https://vault.ninhu.xyz
      path: secret
      version: v2
      caProvider:
        type: Secret
        name: vault-ca
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes-galactica
          role: app-galactica-cloudflare-dns
          serviceAccountRef:
            name: cloudflare-dns
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns-secret
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloudflare-dns-vault
    kind: SecretStore
  target:
    name: cloudflare-dns-secret
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: apps/prod/galactica/cloudflare-dns/api
        property: api-token
