apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-tunnel
  namespace: networking
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cloudflare-tunnel-vault
  namespace: networking
spec:
  provider:
    vault:
      server: https://vault.ninhu.xyz
      path: secret
      version: v2
      caProvider:
        type: Secret
        name: vault-ca
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes-galactica
          role: app-galactica-cloudflare-tunnel
          serviceAccountRef:
            name: cloudflare-tunnel
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secret
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cloudflare-tunnel-vault
    kind: SecretStore
  target:
    name: cloudflare-tunnel-secret
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: apps/prod/galactica/cloudflare-tunnel/tunnel
        property: token
