apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: grafana-vault
  namespace: observability
spec:
  provider:
    vault:
      server: https://vault.ninhu.xyz
      path: secret
      version: v2
      caProvider:
        type: Secret
        name: vault-ca
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes-galactica
          role: app-galactica-grafana
          serviceAccountRef:
            name: grafana
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-database-credentials
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grafana-vault
    kind: SecretStore
  target:
    name: grafana-database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: apps/prod/galactica/grafana/database
        property: username
    - secretKey: password
      remoteRef:
        key: apps/prod/galactica/grafana/database
        property: password
    - secretKey: GF_DATABASE_USER
      remoteRef:
        key: apps/prod/galactica/grafana/database
        property: username
    - secretKey: GF_DATABASE_PASSWORD
      remoteRef:
        key: apps/prod/galactica/grafana/database
        property: password
    - secretKey: admin-user
      remoteRef:
        key: apps/prod/galactica/grafana/database
        property: admin_username
    - secretKey: admin-password
      remoteRef:
        key: apps/prod/galactica/grafana/database
        property: admin_password
