apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cert-manager/issuers
  - cert-manager-vault.yaml
  - cloudflare-dns-vault.yaml
  - cloudflare-tunnel-vault.yaml
  - grafana-vault.yaml
secretGenerator:
  - name: vault-ca
    namespace: cert-manager
    files:
      - ca.crt=vault-ca.crt
    options:
      disableNameSuffixHash: true
  - name: vault-ca
    namespace: observability
    files:
      - ca.crt=vault-ca.crt
    options:
      disableNameSuffixHash: true
  - name: vault-ca
    namespace: networking
    files:
      - ca.crt=vault-ca.crt
    options:
      disableNameSuffixHash: true
