apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  values:
    alertmanager:
      alertmanagerSpec:
        replicas: 1
