apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 30m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
    - name: cloudnative-pg
      namespace: cnpg-system
    - name: external-secrets
      namespace: external-secrets
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: grafana
      version: ">=10.5.0 <11.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    replicas: 1
    serviceMonitor:
      enabled: true
      path: /metrics
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPU: "60"
      targetMemory: ""
      behavior: {}
    serviceAccount:
      create: true
      name: grafana
    deploymentStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    image:
      registry: docker.io
      repository: grafana/grafana
      tag: ""
      sha: ""
      pullPolicy: IfNotPresent
    admin:
      existingSecret: grafana-database-credentials
      userKey: admin-user
      passwordKey: admin-password
    env:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: grafana-rw.observability.svc.cluster.local
      GF_DATABASE_NAME: grafana
      GF_DATABASE_SSL_MODE: disable
    envFromSecrets:
      - name: grafana-database-credentials
    resources: {}
    #  limits:
    #    cpu: 100m
    #    memory: 128Mi
    #  requests:
    #    cpu: 100m
    #    memory: 128Mi
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            uid: prometheus
            type: prometheus
            url: >-
              http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
            access: proxy
            isDefault: true
            editable: false
            jsonData:
              timeInterval: 30s
          - name: Loki
            uid: loki
            type: loki
            url: >-
              http://loki.observability.svc.cluster.local:3100
            access: proxy
            isDefault: false
            editable: false
          - name: Tempo
            uid: tempo
            type: tempo
            url: >-
              http://tempo.observability.svc.cluster.local:3200
            access: proxy
            isDefault: false
            editable: false
    persistence:
      enabled: true
      type: pvc
      storageClassName: longhorn
      accessModes:
        - ReadWriteOnce
      size: 5Gi

      finalizers:
        - kubernetes.io/pvc-protection
