apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../observability-collectors
  - kube-prometheus-stack.yaml
  - loki.yaml
  - tempo.yaml
  - grafana-database.yaml
patches:
  - path: prometheus.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: observability
  - path: alertmanager.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: observability
