apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  values:
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: true
        configReloaders: true
        general: true
        node: true
        kubeProxy: false
        windows: false
    prometheus:
      prometheusSpec:
        retention: 7d
        enableOTLPReceiver: true
        otlp:
          keep_identifying_resource_attributes: true
          promote_resource_attributes:
            - service.instance.id
            - service.name
            - service.namespace
            - deployment.environment.name
            - service.version
            - cloud.availability_zone
            - cloud.region
            - container.name
            - deployment.environment
            - k8s.cluster.name
            - k8s.container.name
            - k8s.cronjob.name
            - k8s.daemonset.name
            - k8s.deployment.name
            - k8s.job.name
            - k8s.namespace.name
            - k8s.pod.name
            - k8s.replicaset.name
            - k8s.statefulset.name
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        additionalScrapeConfigs:
          - job_name: vault
            metrics_path: /v1/sys/metrics
            params:
              format:
                - prometheus
            scheme: https
            scrape_interval: 30s
            scrape_timeout: 25s
            tls_config:
              insecure_skip_verify: true
            static_configs:
              - targets:
                  - vault-active.vault.svc.cluster.local:8200
                labels:
                  component: vault
                  namespace: vault
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
