apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  values:
    replicaCount: 1
    webhook:
      replicaCount: 1
    cainjector:
      replicaCount: 1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  values:
    replicas: 1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  values:
    reloader:
      deployment:
        replicas: 1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  values:
    prometheus:
      prometheusSpec:
        replicas: 1
        externalLabels:
          cluster: pegasus
          environment: non-prod
        additionalScrapeConfigs:
          - job_name: proxmox-ve-exporter
            scrape_interval: 30s
            scrape_timeout: 10s
            static_configs:
              - targets:
                  - hyperion.ninhu.xyz:9221
                labels:
                  instance: proxmox-ve
          - job_name: raspberry-pi-node-exporter
            scrape_interval: 30s
            scrape_timeout: 10s
            static_configs:
              - targets:
                  - rpi.ninhu.xyz:9100
                labels:
                  instance: raspberry-pi
        #remoteWrite:
        #  - url: https://prometheus.andorigna.com/api/v1/write
        #    name: galactica
        storageSpec:
          volumeClaimTemplate:
            spec:
              resources:
                requests:
                  storage: 1Gi
    alertmanager:
      alertmanagerSpec:
        replicas: 1
