- name: area/apps
  color: "0e8a16"
- name: area/clusters
  color: "0e8a16"
- name: area/infrastructure
  color: "0e8a16"
- name: area/taskfiles
  color: "0e8a16"
- name: area/docs
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
