apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-selfsigned
  namespace: vault
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-ca
  namespace: vault
spec:
  isCA: true
  commonName: vault-internal-ca
  secretName: vault-ca
  issuerRef:
    name: vault-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ca
  namespace: vault
spec:
  ca:
    secretName: vault-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: vault-ca
    kind: Issuer
  commonName: vault.vault.svc.cluster.local
  dnsNames:
    - vault.ninhu.xyz
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault-ui
    - vault-ui.vault
    - vault-ui.vault.svc
    - vault-ui.vault.svc.cluster.local
    - vault-active
    - vault-active.vault
    - vault-active.vault.svc
    - vault-active.vault.svc.cluster.local
    - vault-standby
    - vault-standby.vault
    - vault-standby.vault.svc
    - vault-standby.vault.svc.cluster.local
    - vault-0.vault-internal
    - vault-0.vault-internal.vault.svc
    - vault-0.vault-internal.vault.svc.cluster.local
    - vault-1.vault-internal
    - vault-1.vault-internal.vault.svc
    - vault-1.vault-internal.vault.svc.cluster.local
    - vault-2.vault-internal
    - vault-2.vault-internal.vault.svc
    - vault-2.vault-internal.vault.svc.cluster.local
