apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../foundation/cert-manager-issuer.yaml
  - ../secrets/vault-tls.yaml
  - ../secrets/vault-ca-sync.yaml
  - ../secrets/cert-manager-cloudflare.yaml
  - ../observability/grafana-database.yaml
