apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../foundation/cert-manager.yaml
  - ../foundation/metrics-server.yaml
  - ../foundation/reloader.yaml
  - ../networking/envoy-gateway.yaml
  - ../storage/longhorn.yaml
  - ../secrets/vault.yaml
  - ../secrets/external-secrets.yaml
  - ../databases/cloudnative-pg.yaml
  - ../observability/kube-state-metrics.yaml
  - ../observability/kube-prometheus-stack.yaml
  - ../observability/loki.yaml
  - ../observability/tempo.yaml
  - ../observability/alloy.yaml
patches:
  - path: ../observability/prometheus.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: observability
  - path: ../observability/alertmanager.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: observability
