apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/observability-collectors
patches:
  - path: alloy-patches.yaml
  - path: kube-state-metrics-patches.yaml
