apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  values:
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataPath: /var/lib/longhorn
    persistence:
      defaultClassReplicaCount: 2
    longhornManager:
      tolerations: &controlPlaneTolerations
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

    longhornDriver:
      tolerations: *controlPlaneTolerations

    longhornUI:
      tolerations: *controlPlaneTolerations

    longhornAdmissionEngine:
      tolerations: *controlPlaneTolerations
