apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  values:
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataPath: /var/lib/longhorn
    persistence:
      defaultClassReplicaCount: 2
    tolerations: &controlPlaneTolerations
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"

    longhornManager:
      tolerations: *controlPlaneTolerations

    longhornDriver:
      tolerations: *controlPlaneTolerations

    longhornUI:
      tolerations: *controlPlaneTolerations

    longhornAdmissionEngine:
      tolerations: *controlPlaneTolerations
