apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/envoy-gateway
  - namespace.yaml
  - internal-gateway.yaml
patches:
  - path: envoy-gateway-patches.yaml