apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cnpg
  - ../../../../base/grafana-database
patches:
  - path: cnpg-patches.yaml
  - path: database-patches.yaml
