apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/cnpg
  - ../../../../base/observability/grafana-database.yaml
patches:
  - path: cnpg-patches.yaml
  - path: database-patches.yaml
