apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../foundation/namespaces.yaml
  - ../foundation/repositories.yaml
  - ../networking/namespaces.yaml
  - ../networking/repositories.yaml
  - ../storage/namespaces.yaml
  - ../storage/repositories.yaml
  - ../secrets/namespaces.yaml
  - ../secrets/repositories.yaml
  - ../databases/namespaces.yaml
  - ../databases/repositories.yaml
  - ../observability/namespaces.yaml
  - ../observability/repositories.yaml
