apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: galactica-internal
  namespace: networking
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        type: LoadBalancer
        loadBalancerClass: kube-vip.io/kube-vip-class
        loadBalancerIP: 192.168.89.121
        externalTrafficPolicy: Cluster
        annotations:
          kube-vip.io/loadbalancerIPs: 192.168.89.121
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: galactica-internal
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: galactica-internal
    namespace: networking
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: networking
spec:
  gatewayClassName: galactica-internal
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.ninhu.xyz/internal-access: "true"
