apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure.yaml
  - rbac.yaml
  - cnpg.yaml
  - networking-controller.yaml
  - networking.yaml
  - secrets.yaml
  - cloudflare-dns.yaml
  - cloudflare-dns-records.yaml
  - cloudflare-tunnel.yaml
  - databases.yaml
  - observability.yaml
