apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/observability
  - dashboard-proxmox.yaml
  - dashboard-raspberry-pi.yaml
  - proxmox-ve-exporter.yaml
  - raspberry-pi-node-exporter.yaml
patches:
  - path: alloy-patches.yaml
  - path: prometheus-patches.yaml
  - path: database-patches.yaml
  - path: tempo-patches.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: tempo
      namespace: observability
