apiVersion: v1
kind: Service
metadata:
  name: proxmox-ve-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: proxmox-ve-exporter
spec:
  type: ExternalName
  externalName: hyperion.ninhu.xyz
  ports:
    - name: metrics
      port: 9221
      targetPort: 9221
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxmox-ve-exporter
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - observability
  selector:
    matchLabels:
      app.kubernetes.io/name: proxmox-ve-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: instance
          replacement: proxmox-ve
