apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../base/networking
  - ../../base/storage
  - ../../base/databases
patches:
  - path: patches.yaml
  - path: networking-patches.yaml
  - path: storage-patches.yaml
  - path: database-patches.yaml
