apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/kube-system
  - ../../../../base/cert-manager
  - ../../../../base/storage
patches:
  - path: cert-manager-patches.yaml
  - path: storage-patches.yaml